server:
  port: 8004
  
spring:
  profiles: dev
  application:
    name: cloud-demo-provider
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka,http://eureka-server3:8763/eureka
---
server:
  port: 8005
  
spring:
  profiles: test
  application:
    name: cloud-demo-provider
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka,http://eureka-server3:8763/eureka